name: Publish Docker rakaprad/slack-to-telegram-bot
on:
  push:
    branches: [ master ]
  release:
    types:
      - published
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Website landing Dockefile
        run: ls && cat Dockerfile
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: rakaprad/slack-to-telegram-bot
          tag_with_ref: true